spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MoaMoa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tlrbsqkr1!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: psk980331@gmail.com
    password: gxcqpezgxajjlcbd
    properties:
      mail:
        smtp:
          auth: true
          starttls: # 추가 안하면 SMTPSendFailedException
            enalble: true
            required: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace